apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: v1
    meta.helm.sh/release-namespace: v1
  labels:
    app: virtualcluster
  name: v1
  namespace: v1
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - services/proxy
  - pods
  - pods/proxy
  - pods/attach
  - pods/portforward
  - pods/exec
  - pods/log
  - events
  - endpoints
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
