apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: virtualcluster
  name: v1
  namespace: v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: v1
subjects:
- kind: ServiceAccount
  name: vc-v1
  namespace: v1
