apiVersion: v1
kind: Service
metadata:
  labels:
    app: v1-virtualcluster
  name: v1-headless
  namespace: v1
spec:
  clusterIP: None
  ports:
  - name: virtualcluster
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: virtualcluster
    release: v1
  sessionAffinity: None
  type: ClusterIP
