apiVersion: v1
kind: Service
metadata:
  labels:
    app: virtualcluster
  name: v1
  namespace: v1
spec:
  ports:
  - name: virtualcluster
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: virtualcluster
    release: v1
  sessionAffinity: None
  type: ClusterIP

