apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pihole-dnscfg
  name: pihole-dnscfg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi