apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
spec:
  ports:
  - name: "53"
    port: 53
    targetPort: 53
  - name: "80"
    port: 8080
    targetPort: 80
  - name: "443"
    port: 445
    targetPort: 443
  selector:
    app: pihole
  type: LoadBalancer